recommendations = [
    "You're doing great! Keep up the good work!",
    "Happiness radiates like the fragrance from a flower.",
    "You're amazing! Keep shining and spreading positivity.",
    "It's okay to have a bad day. Try to take a deep breath and relax.",
    "Every day is a new beginning. Stay hopeful!",
    "You're stronger than you think. Take it one step at a time.",
    "You're on the right track. Keep focusing on the positives!",
    "Take a moment to reflect and be proud of how far you've come.",
    "Stay steady and calm, and keep pushing forward!",
    "Even small steps forward are progress. You're moving in the right direction.",
    "Remember that growth takes time. Be patient with yourself.",
    "You've got this! Keep going, and don't lose sight of your goals.",
    "Believe in yourself—you are capable of amazing things.",
    "Take time to appreciate how far you've come, even when it feels slow.",
    "Challenges are opportunities in disguise. You are growing every day.",
    "You deserve to feel proud of yourself for all the hard work you've put in.",
    "Trust the journey and know that everything will fall into place.",
    "You're stronger than the obstacles you're facing. Keep going.",
    "Keep your head up—better days are just around the corner.",
    "You have the power to create the change you seek. One step at a time.",
    "Each day is a chance to start fresh. You are doing your best.",
    "You are enough just as you are. Embrace your uniqueness.",
    "Every challenge you face is helping you become stronger and wiser.",
    "Progress, not perfection. You are moving forward, and that’s what matters.",
    "Be kind to yourself today. You are doing the best you can.",
    "You’re not alone. Reach out when you need support. People care.",
    "You are more resilient than you think. Keep moving forward.",
    "It's okay to rest and recharge. You deserve a break.",
    "Your efforts are planting the seeds for future success. Keep nurturing them.",
    "Sometimes slowing down is the best way to move forward.",
    "Keep your heart open to new possibilities and stay hopeful.",
    "You’re capable of handling whatever life throws your way.",
    "Let go of perfection. Focus on progress and growth.",
    "Breathe deeply, trust yourself, and take one day at a time.",
    "You are resilient and resourceful. Trust in your ability to adapt.",
    "Even in difficult times, you are growing stronger and wiser.",
    "The journey is long, but you have the strength to see it through.",
    "Remember, it's okay to ask for help when you need it.",
    "Take pride in how far you’ve come. You’re making amazing progress.",
    "You have everything you need to succeed within you. Keep going.",
    "Stay focused on your goals and trust that you’re moving in the right direction.",
    "You’re doing better than you think you are. Keep up the good work.",
    "It's okay to feel what you're feeling. Give yourself grace.",
    "Celebrate the small wins—they’re all steps toward your bigger goals.",
    "The tough moments will pass. Stay strong and keep your head up.",
    "You’re a work in progress, and that’s something to be proud of.",
    "You are capable, strong, and enough. Keep believing in yourself.",
    "Take time to recharge today. You deserve some rest and self-care.",
    "Don’t compare your journey to others’. You are unique and on your own path.",
    "Focus on what you can control, and let go of the rest.",
    "Every moment is a chance to turn things around. Stay hopeful!",
    "It's okay to feel overwhelmed. Take it one step at a time.",
    "You’ve survived tough times before, and you’ll get through this too.",
    "You are worthy of love, success, and happiness—just as you are.",
    "Each step forward, no matter how small, is a step closer to your goal.",
    "The best is yet to come. Stay optimistic and keep moving forward.",
    "Let today be a reminder of your resilience and strength.",
    "Give yourself permission to take breaks and recharge when you need to.",
    "No matter how hard it seems, you are making progress every day.",
    "Life has ups and downs, but you’re equipped to handle it all.",
    "You have the ability to overcome any obstacle. Stay determined.",
    "Rest when you need to, but never give up on yourself.",
    "Stay patient and trust that things will work out in time.",
    "You are doing the best you can, and that’s more than enough.",
    "It's okay to not have all the answers right now. Trust the process.",
    "Look for the silver linings—there’s always something to be grateful for.",
    "You have an inner strength that can get you through anything.",
    "You are creating a beautiful life, one step at a time.",
    "Trust that you’re exactly where you’re meant to be on your journey.",
    "Difficult roads often lead to beautiful destinations. Keep going.",
    "Take a deep breath, and trust that everything will be okay.",
    "You are more than capable of achieving great things. Keep believing.",
    "It’s okay to pause and reflect. Sometimes the greatest clarity comes from stillness.",
    "Keep nurturing your dreams. They are closer than you think.",
    "You’re resilient and resourceful. Trust in yourself and keep going.",
    "You are enough, just as you are. Embrace your journey and growth.",
    "One step at a time, you are moving closer to where you want to be.",
    "When things get tough, remember how far you've come already."
]
